export const calendarStyles = String.raw`
.calendar-layout{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:1rem;align-items:start}
#calendar-planner{grid-column:1/-1}
.calendar-top{display:grid;grid-template-columns:minmax(0,1fr) 18rem}.calendar-top>div{min-width:0}

.calendar-toolbar,.calendar-views{display:flex;align-items:center;gap:.5rem;flex-wrap:wrap}.calendar-toolbar{padding:1rem;justify-content:space-between}.calendar-toolbar strong{font-size:1.1rem}
.calendar-toolbar button,.calendar-form button,.calendar-types button{border:1px solid var(--border);border-radius:.5rem;padding:.5rem .7rem;background:var(--panel2);color:var(--text)}
.calendar-toolbar button[aria-pressed="true"],.calendar-form button[type="submit"],.calendar-types button[type="submit"]{background:var(--accent);color:var(--accentText)}
.calendar-body{padding:0 1rem 1rem;min-height:0}.calendar-scroll{max-height:27rem;overflow:auto;border:1px solid var(--border);border-radius:.7rem}
.calendar-days{display:grid;min-width:760px;grid-template-columns:3rem repeat(7,minmax(0,1fr))}.calendar-days.day{min-width:280px;grid-template-columns:3rem minmax(0,1fr)}
.calendar-day-head{position:sticky;top:0;z-index:3;height:2.8rem;padding:.6rem .2rem;background:var(--panel);color:var(--text);text-align:center;font-weight:600;border:0;border-bottom:1px solid var(--border)}
.calendar-all-day{position:sticky;top:2.8rem;z-index:2;padding:.25rem;min-height:2.25rem;border-right:1px solid var(--border);background:var(--panel2)}
.calendar-hours,.calendar-timeline{height:1152px;position:relative}.calendar-timeline{border-right:1px solid var(--border);background:repeating-linear-gradient(to bottom,transparent 0,transparent 47px,var(--border) 47px,var(--border) 48px)}.calendar-hours span{position:absolute;font-size:.65rem;color:var(--muted);left:.2rem}
.calendar-event{border:1px solid var(--border);border-left:3px solid var(--event-color,#3378e6);border-radius:.45rem;background:color-mix(in srgb,var(--event-color,#3378e6) 16%,var(--panel));color:var(--text);padding:.3rem;font-size:.75rem;overflow:hidden;text-align:left;overflow-wrap:anywhere}
.calendar-event[data-kind="holiday"]{border-left-style:dashed}.calendar-timeline .calendar-event{position:absolute}.calendar-all-day .calendar-event{display:block;width:100%;margin-bottom:.2rem}
.calendar-year{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:.6rem;height:100%;min-height:24rem;grid-auto-rows:1fr}.calendar-month{border:1px solid var(--border);border-radius:.6rem;padding:.5rem;min-width:0}.calendar-month h3{margin:0 0 .4rem;font-size:.75rem}.calendar-current-month{border-color:var(--accent)}.calendar-current-month h3{color:var(--accent)}
.calendar-month-grid{display:grid;grid-template-columns:repeat(7,minmax(0,1fr));gap:.12rem;text-align:center}.calendar-month-grid span{font-size:.55rem;color:var(--muted)}.calendar-month-grid button{border:0;background:transparent;color:var(--text);border-radius:.3rem;padding:.1rem 0;position:relative;font-size:.65rem;line-height:1.2}.calendar-month-grid button:hover{background:var(--panel2)}.calendar-month-grid button.today{outline:1px solid var(--accent);background:var(--panel2)}
.calendar-month-board{display:grid;grid-template-columns:repeat(7,minmax(0,1fr));border:1px solid var(--border);border-radius:.5rem;overflow:hidden}.calendar-month-cell{min-height:5rem;padding:.3rem;border-right:1px solid var(--border);border-bottom:1px solid var(--border);min-width:0}.calendar-month-cell.outside{opacity:.55}.calendar-month-cell>button:first-child{border:0;border-radius:.4rem;background:var(--panel2);color:var(--text);padding:.3rem}.calendar-month-cell .calendar-event{display:block;width:100%;margin-top:.2rem;font-size:.65rem}
.calendar-now{position:absolute;left:0;right:0;border-top:1px solid #e45b68;pointer-events:none;z-index:2}.calendar-today-column{background-color:color-mix(in srgb,var(--accent) 5%,var(--panel))}
.calendar-form{display:grid;gap:.45rem;padding:.5rem 1rem 1rem}.calendar-form label,.calendar-types label{display:grid;gap:.35rem;font-size:.75rem;color:var(--muted)}
.calendar-form input,.calendar-form select,.calendar-form textarea,.calendar-types input,.calendar-types select{min-width:0;width:100%;background:var(--panel2);color:var(--text);border:1px solid var(--border);border-radius:.4rem;padding:.45rem;font-size:.8rem}
.calendar-form textarea{height:3.5rem;resize:vertical}.calendar-field-pair{display:grid;grid-template-columns:1fr 1fr;gap:.5rem}.calendar-form [hidden]{display:none}.calendar-actions{display:flex;gap:.4rem;justify-content:flex-end;align-items:center}
.calendar-weekends{display:flex!important;align-items:center}.calendar-weekends input{width:auto!important}.calendar-toolbar select{max-width:18rem;min-width:0;background:var(--panel2);color:var(--text);border:1px solid var(--border);border-radius:.4rem;padding:.5rem}.calendar-toolbar small{color:var(--muted);font-size:.7rem}.calendar-form input[type="color"],.calendar-types input[type="color"]{width:4.5rem;height:2.4rem;padding:.2rem;cursor:pointer}
.calendar-agenda,.calendar-types{padding:1rem}.calendar-agenda{border-top:1px solid var(--border)}.calendar-agenda h3{font-size:.9rem;margin:0 0 .6rem}.calendar-agenda button{display:block;width:100%;margin:.3rem 0;padding:.6rem}.calendar-agenda p,.calendar-types p{font-size:.8rem;color:var(--muted)}
.calendar-types form{display:grid;grid-template-columns:minmax(8rem,2fr) minmax(6rem,1fr) minmax(8rem,1fr) auto auto;align-items:end;gap:.75rem;margin:1rem 0 .4rem}.calendar-types small{font-size:.7rem;color:var(--muted)}
.calendar-type-row{display:flex;gap:.4rem;align-items:center;margin:.6rem 0;font-size:.8rem}.calendar-type-row span{flex:1;overflow-wrap:anywhere;border-left:3px solid var(--event-color);padding-left:.5rem}
.calendar-status{padding:0 1rem;font-size:.8rem;color:var(--muted)}.calendar-status:empty{display:none}.calendar-status[data-error="true"]{color:#c94d54}.calendar-form #calendar-unit{margin:.4rem 0;padding:0;font-size:.8rem}.calendar-card h2{margin-bottom:.5rem!important}.app>aside nav button[data-page="calendar"] .ui-icon{color:#9863c9}
@media(max-width:1000px){.calendar-top{grid-template-columns:minmax(0,1fr)}#calendar-tools{border-left:0;border-top:1px solid var(--border)}.calendar-layout{grid-template-columns:minmax(0,1fr)}.calendar-types form{grid-template-columns:repeat(2,minmax(0,1fr))}.calendar-types .calendar-actions{grid-column:1/-1}}
@media(max-width:500px){.calendar-year{grid-template-columns:repeat(3,minmax(0,1fr));grid-template-rows:repeat(4,minmax(0,1fr));min-height:32rem}.calendar-types form{grid-template-columns:minmax(0,1fr)}}

.calendar-year{height:auto;min-height:0;grid-template-columns:repeat(3,minmax(0,1fr));grid-auto-rows:auto;gap:.8rem}.calendar-month{padding:.6rem;display:flex;flex-direction:column}.calendar-month h3{font-size:.85rem}.calendar-month-grid{grid-template-rows:none;flex:none;gap:.2rem}.calendar-month-grid button{height:1.6rem;font-size:.8rem;border:1px solid transparent;display:block}.calendar-month-grid button.has-entry{font-weight:750;background:color-mix(in srgb,var(--event-color) 32%,var(--panel));border-color:var(--event-color);box-shadow:inset 0 -3px var(--event-color)}.calendar-month-grid button[data-holiday="true"]{border-style:dashed}.calendar-year-agenda{display:grid;gap:.25rem;margin-top:.5rem}.calendar-year-agenda .calendar-event{font-size:.7rem}.calendar-year-agenda>button:not(.calendar-event){border:0;background:transparent;color:var(--accent);text-align:left;font-size:.75rem}.calendar-types form{grid-template-columns:minmax(0,1fr) minmax(0,1fr);align-items:end}.calendar-types .calendar-actions{align-self:end}.calendar-balance-scroll{padding:0 1rem 1rem;overflow:auto}.calendar-balance-table{border-collapse:collapse;width:100%;font-size:.8rem;text-align:left}.calendar-balance-table th,.calendar-balance-table td{padding:.7rem .4rem;border-bottom:1px solid var(--border)}.calendar-balance-table th{color:var(--muted);font-weight:600}.calendar-balance-table td:first-child{border-left:3px solid var(--event-color);padding-left:.6rem}#calendar-totals{display:table-row-group;margin:0}#calendar-type-form>[hidden]{display:none}@media(max-width:1000px){.calendar-year{grid-template-columns:repeat(3,minmax(0,1fr))}}@media(max-width:650px){.calendar-year{grid-template-columns:repeat(2,minmax(0,1fr))}}
.calendar-top{display:block}.calendar-top>div{width:100%}.calendar-toolbar{gap:.75rem;padding:1rem 1.25rem}.calendar-views{gap:.35rem}.calendar-views[aria-label]{padding:.25rem;border-radius:.65rem;background:var(--panel2)}.calendar-views[aria-label] button{border-color:transparent;background:transparent}.calendar-views[aria-label] button[aria-pressed="true"]{background:var(--panel);color:var(--accent);box-shadow:0 1px 5px #0001}.calendar-views #calendar-add{background:var(--accent);color:var(--accentText);margin-right:.4rem;display:flex;align-items:center;gap:.4rem}.calendar-source-toolbar{padding-top:0;justify-content:space-between}.calendar-source-controls{display:flex;align-items:center;gap:.4rem}.calendar-body{padding:0 1.25rem 1.25rem}.calendar-scroll{max-height:36rem;scrollbar-width:thin;scrollbar-color:var(--border) transparent;background:var(--panel)}.calendar-day-head{font-size:.8rem;height:3rem}.calendar-days{grid-template-columns:4rem repeat(7,minmax(0,1fr));min-width:650px}.calendar-days.day{grid-template-columns:4rem minmax(0,1fr)}.calendar-hours span{font-size:.7rem;padding-top:.25rem}.calendar-all-day{top:3rem;min-height:2.6rem}.calendar-all-day-add{float:right;border:0;background:none;color:var(--muted);padding:.25rem;opacity:.5}.calendar-all-day-add:hover{color:var(--accent);opacity:1}.calendar-slot{position:absolute;left:0;right:0;height:48px;border:0;background:transparent;z-index:0}.calendar-slot:hover,.calendar-slot:focus-visible{background:color-mix(in srgb,var(--accent) 8%,transparent);outline:1px solid var(--accent);outline-offset:-1px}.calendar-timeline .calendar-event{z-index:1}.calendar-agenda{padding:.8rem 1.25rem}.calendar-agenda[hidden]{display:none}.calendar-agenda>div{display:flex;gap:.5rem;flex-wrap:wrap}.calendar-agenda button{width:auto}.calendar-agenda h3{font-size:.8rem;color:var(--muted)}
.calendar-entry-dialog{width:min(34rem,calc(100vw - 2rem));max-height:calc(100vh - 3rem);padding:0;border:1px solid var(--border);border-radius:1rem;background:var(--panel);color:var(--text);box-shadow:var(--shadow);overflow:auto}.calendar-entry-dialog::backdrop{background:#0b122866;backdrop-filter:blur(3px)}.calendar-dialog-header{display:flex;align-items:center;justify-content:space-between;padding:1rem 1.25rem;border-bottom:1px solid var(--border)}.calendar-dialog-header h2{font-size:1rem!important;letter-spacing:0!important;margin:0!important;text-transform:none!important;padding:0!important;border:0!important;background:none!important}.calendar-entry-dialog .calendar-form{padding:1.25rem;gap:.8rem;grid-template-columns:1fr 1fr}.calendar-entry-dialog .calendar-form>label:nth-child(2),.calendar-entry-dialog #calendar-times,.calendar-entry-dialog #calendar-leave,.calendar-entry-dialog .calendar-form>label:has(textarea),.calendar-entry-dialog .calendar-actions{grid-column:1/-1}.calendar-form label,.calendar-types label{font-size:.8rem;font-weight:550}.calendar-form input,.calendar-form select,.calendar-form textarea,.calendar-types input{font-size:.85rem;padding:.65rem;border-radius:.5rem}.calendar-entry-dialog #calendar-leave{display:grid;grid-template-columns:1fr 1fr;gap:.65rem}.calendar-entry-dialog #calendar-leave[hidden]{display:none}.calendar-entry-dialog #calendar-unit{grid-column:1/-1;font-weight:400}.calendar-entry-dialog .calendar-actions{border-top:1px solid var(--border);padding-top:.85rem}.calendar-entry-dialog #calendar-save{display:flex;gap:.4rem;align-items:center}.calendar-types{padding:.4rem 1.25rem 1rem}.calendar-type-row{padding:.6rem;border:1px solid var(--border);border-radius:.55rem;background:var(--panel2)}.calendar-type-row .icon-button{flex:none}.calendar-balance-scroll{padding:.75rem 1.25rem 1.25rem}.calendar-balance-table th{font-size:.75rem}.calendar-balance-table td{padding:.85rem .5rem}.calendar-types p{font-size:.75rem}.calendar-entry-dialog .calendar-weekends{font-weight:400}.calendar-source-controls select{width:15rem}.calendar-status{padding:0 1.25rem}.calendar-month-cell>button:first-child:hover{background:var(--accent);color:var(--accentText)}
#team-calendar-connect{padding:1rem 1.25rem;grid-template-columns:minmax(0,1fr) auto;gap:.7rem}#team-calendar-connect>label:first-child{grid-column:1/-1}#team-calendar-connect>label:nth-child(2){grid-column:2;grid-row:2}#team-calendar-connect>label:nth-child(3){grid-column:1;grid-row:2}#team-calendar-connect>button{justify-self:end;grid-column:1/-1;width:2.6rem;height:2.6rem;padding:.5rem}#team-calendar-list{padding:0 1.25rem 1rem}#team-calendar-list .workspace-row{display:flex;gap:.4rem;align-items:center;border:1px solid var(--border);border-radius:.5rem;padding:.65rem;margin-bottom:.5rem;background:var(--panel2)}#team-calendar-list .workspace-row>div{flex:1;min-width:0}#team-calendar-list strong,#team-calendar-list small{display:block}#team-calendar-list small{font-size:.75rem;color:var(--muted)}#team-calendar-list p{font-size:.8rem}#team-calendar-message:empty{display:none}#team-calendar-connect input[type="color"]{width:3rem}#team-calendar-connect label{font-size:.8rem}

`;

export const calendarHtml = String.raw`
<section class="page" data-view="calendar" aria-label="Calendar planner" hidden><div class="calendar-layout">
<article id="calendar-planner" class="jira-card calendar-card"><h2>Planner</h2><div class="calendar-top"><div><div class="calendar-toolbar"><div class="calendar-views"><button id="calendar-prev" aria-label="Previous period" title="Previous period"><svg class="ui-icon" viewBox="0 0 24 24"><path d="m15 5-7 7 7 7"/></svg></button><button id="calendar-next" aria-label="Next period" title="Next period"><svg class="ui-icon" viewBox="0 0 24 24"><path d="m9 5 7 7-7 7"/></svg></button><button id="calendar-today">Today</button><strong id="calendar-period"></strong></div><div class="calendar-views" aria-label="Calendar view"><button id="calendar-add" class="primary-icon-button" type="button"><svg class="ui-icon"><use href="#i-plus"/></svg> New entry</button><button data-calendar-view="day">Day</button><button data-calendar-view="week">Week</button><button data-calendar-view="month">Month</button><button data-calendar-view="year">Year</button></div></div><div class="calendar-toolbar calendar-source-toolbar"><div class="calendar-source-controls"><select id="calendar-source-select" aria-label="Connected Team Calendar"><option value="">Team Calendars</option></select><button id="calendar-source-refresh" class="icon-button" type="button" aria-label="Refresh selected Team Calendar" title="Refresh selected Team Calendar for this year"><svg class="ui-icon"><use href="#i-refresh"/></svg></button></div><small>Click a date or time to add an entry.</small></div><p id="calendar-page-status" class="calendar-status" role="status" aria-live="polite"></p><div id="calendar-body" class="calendar-body"></div></div>
<dialog id="calendar-entry-dialog" class="calendar-entry-dialog" aria-labelledby="calendar-form-heading"><header class="calendar-dialog-header"><h2 id="calendar-form-heading">New entry</h2><button id="calendar-dialog-close" class="icon-button" type="button" aria-label="Close entry" title="Close entry"><svg class="ui-icon"><use href="#i-close"/></svg></button></header><p id="calendar-status" class="calendar-status" role="status" aria-live="polite"></p>
<form id="calendar-form" class="calendar-form"><label>Entry type<select name="kind"><option value="plan">Plan</option><option value="holiday">Holiday</option><option value="leave">Leave</option></select></label><label>Title<input name="title" maxlength="200" required /></label><label>Start date<input name="startDate" type="date" min="1900-01-01" max="2100-12-31" required /></label><label id="calendar-end-date">End date<input name="endDate" type="date" min="1900-01-01" max="2100-12-31" /></label><div id="calendar-times" class="calendar-field-pair"><label>Start time<input name="startTime" type="time" /></label><label>End time<input name="endTime" type="time" /></label></div><div id="calendar-leave"><label>Leave type<select name="leaveTypeId"></select></label><label class="calendar-weekends"><input name="includeWeekends" type="checkbox" checked />Include weekends</label><label id="calendar-leave-duration">Duration<select name="leaveDuration"><option value="full">Full days</option><option value="half">Half day</option></select></label><label id="calendar-leave-quantity" hidden><span id="calendar-quantity-label">Hours</span><input name="quantity" type="number" min="0.01" max="10000" step="any" /></label><p id="calendar-unit" class="jira-summary"></p></div><label>Agenda<textarea name="agenda" maxlength="5000" rows="3"></textarea></label><label id="calendar-entry-color">Color<input name="color" type="color" value="#3378e6" title="Choose a color" /></label><div class="calendar-actions"><button type="button" id="calendar-cancel">Cancel</button><button type="button" id="calendar-delete" aria-label="Delete calendar entry" title="Delete calendar entry" hidden><svg class="ui-icon"><use href="#i-trash"/></svg></button><button type="submit" id="calendar-save" aria-label="Save calendar entry" title="Save calendar entry"><svg class="ui-icon"><use href="#i-check"/></svg> Save</button></div></form></dialog>
<section class="calendar-agenda"><h3 id="calendar-agenda-heading">Agenda</h3><div id="calendar-agenda-list"></div></section></div></article>
<article id="calendar-leave-types" class="jira-card calendar-card"><h2>Leave manager</h2><section class="calendar-types"><form id="calendar-type-form"><label>Type name<input name="name" maxlength="80" required /></label><input name="unit" type="hidden" value="days" /><label>Annual allowance (days)<input name="count" type="number" min="0" max="10000" step="0.5" /></label><label>Color<input name="color" type="color" value="#3378e6" title="Choose a color" /></label><div class="calendar-actions"><button type="button" id="calendar-type-cancel">Clear</button><button type="submit" aria-label="Save leave type" title="Save leave type"><svg class="ui-icon"><use href="#i-check"/></svg></button></div></form><p id="calendar-type-unit">Days, including half days. Leave allowance blank for no limit.</p><div id="calendar-type-list"></div></section></article>
<article id="calendar-balances" class="jira-card calendar-card"><h2><span id="calendar-totals-heading">Leave balances</span></h2><div class="calendar-balance-scroll"><table class="calendar-balance-table"><thead><tr><th scope="col">Leave type</th><th scope="col">Annual count</th><th scope="col">Availed</th><th scope="col">Remaining</th></tr></thead><tbody id="calendar-totals"></tbody></table><p id="calendar-balances-empty" class="jira-summary">Add a leave type in Leave manager.</p></div></article></div></section>
`;

export const calendarScript = String.raw`
(()=>{
const root=document.querySelector('[data-view="calendar"]'),body=root.querySelector('#calendar-body'),form=root.querySelector('#calendar-form'),typeForm=root.querySelector('#calendar-type-form'),status=root.querySelector('#calendar-status'),dialog=root.querySelector('#calendar-entry-dialog');
const dateKey=date=>String(date.getFullYear()).padStart(4,'0')+'-'+String(date.getMonth()+1).padStart(2,'0')+'-'+String(date.getDate()).padStart(2,'0');
const fromKey=key=>new Date(key+'T12:00:00');
const shift=(date,days)=>{const next=new Date(date);next.setDate(next.getDate()+days);return next};
const field=name=>form.elements.namedItem(name),typeField=name=>typeForm.elements.namedItem(name);
let selected=new Date(),view=['day','week','month','year'].includes(savedState.calendarView)?savedState.calendarView:'week',state={year:0,entries:[],leaveTypes:[]},editing='',editingType='',pending=false,pendingDate='',pendingAction='',previousStart='';
const years=new Map(),loading=new Set();
const message=(text,error=false)=>{for(const target of [status,root.querySelector('#calendar-page-status')]){target.textContent=text;target.dataset.error=String(error)}};
const lock=value=>{pending=value;root.querySelectorAll('form button,form input,form select,form textarea').forEach(control=>control.disabled=value);if(!value)unitChanged()};
const request=request=>{if(pending)return;pendingAction=request.type;lock(true);message(request.type==='calendar.source.refresh'?'Refreshing calendar…':'Saving…');vscode.postMessage(request)};
const overlaps=(entry,key)=>entry.startDate<=key&&entry.endDate>=key;
const entryLabel=entry=>entry.sourceId?entry.title+' · '+entry.sourceName+' · '+(entry.startTime?entry.startTime+'–'+entry.endTime:'All day'):entry.title+' · '+(entry.kind==='plan'?entry.startTime+'–'+entry.endTime:entry.kind==='holiday'?'Holiday':entry.quantity+' '+(state.leaveTypes.find(type=>type.id===entry.leaveTypeId)?.unit||'')+' leave');
const legacyColors={blue:'#3378e6',teal:'#159d89',amber:'#d58a16',pink:'#d65b79'};
const colorHex=color=>Object.hasOwn(legacyColors,color)?legacyColors[color]:(/^#[a-f0-9]{6}$/i.test(color)?color:'#3378e6');
const paint=(element,color)=>{element.dataset.color=color;element.style.setProperty('--event-color',colorHex(color))};
const entryButton=entry=>{const element=document.createElement('button');element.type='button';element.className='calendar-event';paint(element,entryColor(entry));element.dataset.kind=entry.kind;element.textContent=entryLabel(entry);element.title=entryLabel(entry);element.setAttribute('aria-label',(entry.sourceId?'View read-only ':'Edit ')+entryLabel(entry));element.addEventListener('click',()=>entry.sourceId?vscode.postMessage({type:'calendar.source.event',year:Number(entry.startDate.slice(0,4)),id:entry.id}):edit(entry));return element};
const entryColor=entry=>entry.kind==='leave'?(state.leaveTypes.find(type=>type.id===entry.leaveTypeId)?.color||entry.color):entry.color;
const kindChanged=()=>{const plan=field('kind').value==='plan',leave=field('kind').value==='leave';root.querySelector('#calendar-times').hidden=!plan;root.querySelector('#calendar-end-date').hidden=plan;root.querySelector('#calendar-leave').hidden=!leave;field('startTime').required=plan;field('endTime').required=plan;field('endDate').required=!plan;field('leaveTypeId').required=leave;root.querySelector('#calendar-entry-color').hidden=leave;unitChanged()};
const eligibleDays=()=>{const start=field('startDate').value,end=field('endDate').value;if(!start||!end||end<start)return 0;let days=0;for(const date=new Date(start+'T00:00:00Z');date.toISOString().slice(0,10)<=end;date.setUTCDate(date.getUTCDate()+1)){const key=date.toISOString().slice(0,10);if((!field('includeWeekends').checked&&[0,6].includes(date.getUTCDay()))||state.entries.some(entry=>entry.kind==='holiday'&&overlaps(entry,key)))continue;days++}return days};
const leaveQuantity=()=>state.leaveTypes.find(type=>type.id===field('leaveTypeId').value)?.unit==='days'?(eligibleDays()?(field('leaveDuration').value==='half'?0.5:eligibleDays()):0):Number(field('quantity').value);
const unitChanged=()=>{const type=state.leaveTypes.find(type=>type.id===field('leaveTypeId').value),days=type?.unit==='days',leave=field('kind').value==='leave';if(!days||!leave)field('leaveDuration').value='full';root.querySelector('#calendar-leave-duration').hidden=!days;root.querySelector('#calendar-leave-quantity').hidden=!type||days;field('quantity').required=leave&&!!type&&!days;field('quantity').disabled=pending||!leave||!type||days;root.querySelector('#calendar-quantity-label').textContent=type?.unit||'Hours';const quantity=leaveQuantity();root.querySelector('#calendar-unit').textContent=type?(days?(Number.isFinite(quantity)&&quantity>0?quantity+' days. Holidays excluded; weekends '+(field('includeWeekends').checked?'included.':'excluded.'):'Choose a valid date range.'):type.unit):'Create a leave type below first.';};
field('includeWeekends').addEventListener('change',unitChanged);
const reset=()=>{editing='';form.reset();field('startDate').value=dateKey(selected);field('endDate').value=dateKey(selected);previousStart=field('startDate').value;field('leaveDuration').value='full';root.querySelector('#calendar-delete').hidden=true;root.querySelector('#calendar-form-heading').textContent='New entry';kindChanged()};
field('startDate').addEventListener('change',()=>{if(field('endDate').value===previousStart||!field('endDate').value||field('endDate').value<field('startDate').value||field('leaveDuration').value==='half')field('endDate').value=field('startDate').value;previousStart=field('startDate').value;unitChanged()});
field('endDate').addEventListener('change',()=>{if(field('endDate').value!==field('startDate').value)field('leaveDuration').value='full';unitChanged()});
field('leaveDuration').addEventListener('change',()=>{if(field('leaveDuration').value==='half')field('endDate').value=field('startDate').value;unitChanged()});
const edit=entry=>{if(pending)return;editing=entry.id;for(const name of ['kind','title','startDate','endDate','startTime','endTime','agenda','color','leaveTypeId','quantity'])field(name).value=name==='color'?colorHex(entry.color):String(entry[name]);previousStart=entry.startDate;field('includeWeekends').checked=entry.includeWeekends!==false;field('leaveDuration').value=entry.quantity===0.5?'half':'full';root.querySelector('#calendar-delete').hidden=false;root.querySelector('#calendar-form-heading').textContent='Edit '+entry.kind;kindChanged();if(!dialog.open)dialog.showModal();field('title').focus()};
const openEntry=(date,time='09:00')=>{if(pending)return;choose(date);reset();field('startTime').value=time;const hour=Math.min(23,Number(time.slice(0,2))+1);field('endTime').value=String(hour).padStart(2,'0')+':'+(Number(time.slice(0,2))===23?'59':'00');message('');if(!dialog.open)dialog.showModal();field('title').focus()};
const closeEntry=()=>{if(pending)return;dialog.close();root.querySelector('#calendar-add').focus()};
root.querySelector('#calendar-add').addEventListener('click',()=>openEntry(selected));root.querySelector('#calendar-dialog-close').addEventListener('click',closeEntry);dialog.addEventListener('cancel',event=>{if(pending)event.preventDefault()});
const loadYear=year=>{if(year<1900||year>2100||loading.has(year))return;loading.add(year);vscode.postMessage({type:'calendar.refresh',year})};
const refresh=()=>{const year=selected.getFullYear();if(years.has(year))state=years.get(year);if(state.year!==year){message('Loading calendar…');loadYear(year)}render()};
const choose=date=>{if(date.getFullYear()<1900||date.getFullYear()>2100)return;selected=date;refresh();if(!editing&&!pending){field('startDate').value=field('endDate').value=dateKey(selected);previousStart=field('startDate').value;unitChanged()}};
const renderYear=(entries,year)=>{
const grid=document.createElement('div');grid.className='calendar-year';for(let month=0;month<12;month++){const article=document.createElement('section'),heading=document.createElement('h3'),days=document.createElement('div');article.className='calendar-month';article.classList.toggle('calendar-current-month',month===selected.getMonth());heading.textContent=new Date(year,month,1).toLocaleDateString(undefined,{month:'long'});days.className='calendar-month-grid';['M','T','W','T','F','S','S'].forEach(label=>{const span=document.createElement('span');span.textContent=label;days.append(span)});const offset=(new Date(year,month,1).getDay()+6)%7;for(let n=0;n<offset;n++)days.append(document.createElement('span'));for(let day=1;day<=new Date(year,month+1,0).getDate();day++){const date=new Date(year,month,day,12),dayKey=dateKey(date),items=entries.filter(entry=>overlaps(entry,dayKey)),button=document.createElement('button');button.type='button';button.textContent=String(day);button.title=date.toLocaleDateString()+(items.length?' · '+items.slice(0,5).map(entryLabel).join('; '):'');button.setAttribute('aria-label',button.title);if(items.length){const colors=[...new Set(items.map(entry=>colorHex(entryColor(entry))))];paint(button,colors[0]);button.classList.toggle('has-entry',true);button.dataset.holiday=String(items.some(entry=>entry.kind==='holiday'));if(colors.length>1)button.style.background='linear-gradient(135deg,'+colors.map(color=>'color-mix(in srgb,'+color+' 35%,var(--panel))').map((color,index)=>color+' '+(index*100/colors.length)+'%,'+color+' '+((index+1)*100/colors.length)+'%').join(',')+')'}button.classList.toggle('today',dayKey===dateKey(new Date()));button.addEventListener('click',()=>openEntry(date));days.append(button)}const monthEntries=entries.filter(entry=>entry.startDate<=dateKey(new Date(year,month+1,0,12))&&entry.endDate>=dateKey(new Date(year,month,1,12))),agenda=document.createElement('div');agenda.className='calendar-year-agenda';monthEntries.slice(0,3).forEach(entry=>agenda.append(entryButton(entry)));if(monthEntries.length>3){const more=document.createElement('button');more.type='button';more.textContent='View '+(monthEntries.length-3)+' more';more.addEventListener('click',()=>{view='month';savedState.calendarView=view;vscode.setState(savedState);choose(new Date(year,month,1,12))});agenda.append(more)}article.append(heading,days,agenda);grid.append(article)}body.replaceChildren(grid);
};
const renderTimeline=(target,dates,entries,day)=>{
const scroll=document.createElement('div'),grid=document.createElement('div');scroll.className='calendar-scroll';grid.className='calendar-days'+(day?' day':'');const blank=document.createElement('div');blank.className='calendar-day-head';grid.append(blank);dates.forEach(date=>{const heading=document.createElement('button');heading.type='button';heading.className='calendar-day-head';heading.textContent=date.toLocaleDateString(undefined,{weekday:'short',day:'numeric'});heading.title='Show day';heading.addEventListener('click',()=>{view='day';savedState.calendarView=view;vscode.setState(savedState);choose(date)});grid.append(heading)});const allLabel=document.createElement('div');allLabel.className='calendar-all-day';allLabel.textContent='All day';grid.append(allLabel);dates.forEach(date=>{const row=document.createElement('div');row.className='calendar-all-day';row.addEventListener('click',event=>{if(event.target===row)openEntry(date)});const add=iconButton('plus','Add entry on '+date.toLocaleDateString(),()=>openEntry(date));add.className='calendar-all-day-add';row.append(add);entries.filter(entry=>!entry.startTime&&overlaps(entry,dateKey(date))).forEach(entry=>row.append(entryButton(entry)));grid.append(row)});const hours=document.createElement('div');hours.className='calendar-hours';for(let hour=0;hour<24;hour++){const label=document.createElement('span');label.style.top=(hour*48)+'px';label.textContent=String(hour).padStart(2,'0')+':00';hours.append(label)}grid.append(hours);
dates.forEach(date=>{const column=document.createElement('div');column.className='calendar-timeline';for(let hour=0;hour<24;hour++){const slot=document.createElement('button'),time=String(hour).padStart(2,'0')+':00';slot.type='button';slot.className='calendar-slot';slot.style.top=(hour*48)+'px';slot.title='Add entry · '+date.toLocaleDateString()+' '+time;slot.setAttribute('aria-label',slot.title);slot.addEventListener('click',()=>openEntry(date,time));column.append(slot)}if(dateKey(date)===dateKey(new Date())){column.classList.toggle('calendar-today-column',true);const now=document.createElement('div');now.className='calendar-now';const clock=new Date();now.style.top=((clock.getHours()*60+clock.getMinutes())*.8)+'px';column.append(now)}const minutes=time=>Number(time.slice(0,2))*60+Number(time.slice(3)),items=entries.filter(entry=>!!entry.startTime&&entry.startDate===dateKey(date)).sort((a,b)=>a.startTime.localeCompare(b.startTime));
const clusters=[];let cluster=[],until=0;items.forEach(entry=>{if(cluster.length&&minutes(entry.startTime)>=until){clusters.push(cluster);cluster=[];until=0}cluster.push(entry);until=Math.max(until,minutes(entry.endTime),minutes(entry.startTime)+25)});if(cluster.length)clusters.push(cluster);clusters.forEach(group=>{const ends=[],lanes=group.map(entry=>{let lane=ends.findIndex(end=>end<=minutes(entry.startTime));if(lane<0)lane=ends.length;ends[lane]=Math.max(minutes(entry.endTime),minutes(entry.startTime)+25);return lane});group.forEach((entry,index)=>{const button=entryButton(entry);button.style.top=(minutes(entry.startTime)*.8)+'px';button.style.height=Math.max(20,(minutes(entry.endTime)-minutes(entry.startTime))*.8)+'px';button.style.left=(lanes[index]*100/ends.length)+'%';button.style.width=(100/ends.length)+'%';column.append(button)})});grid.append(column)});scroll.append(grid);target.replaceChildren(scroll);scroll.scrollTop=8*48;dates.forEach(date=>{if(!years.has(date.getFullYear()))loadYear(date.getFullYear())});

};
const renderMonth=(entries,year)=>{const grid=document.createElement('div');grid.className='calendar-month-board';['Mon','Tue','Wed','Thu','Fri','Sat','Sun'].forEach(label=>{const heading=document.createElement('div');heading.className='calendar-day-head';heading.textContent=label;grid.append(heading)});const first=new Date(year,selected.getMonth(),1,12),start=shift(first,-((first.getDay()+6)%7));for(let i=0;i<42;i++){const date=shift(start,i),cell=document.createElement('div'),button=document.createElement('button');cell.className='calendar-month-cell'+(date.getMonth()!==selected.getMonth()?' outside':'');button.type='button';button.textContent=String(date.getDate());button.title=date.toLocaleDateString();button.setAttribute('aria-label',button.title);button.addEventListener('click',()=>openEntry(date));cell.append(button);cell.addEventListener('click',event=>{if(event.target===cell)openEntry(date)});entries.filter(entry=>overlaps(entry,dateKey(date))).forEach(entry=>cell.append(entryButton(entry)));grid.append(cell);if(!years.has(date.getFullYear()))loadYear(date.getFullYear())}body.replaceChildren(grid)};
const render=()=>{
const sourceSelect = root.querySelector("#calendar-source-select"),   sourceId = sourceSelect.value; sourceSelect.replaceChildren(); const placeholder = document.createElement("option"); placeholder.value = ""; placeholder.textContent = "Team Calendars"; sourceSelect.append(placeholder); for (const source of state.sources || []) {   const option = document.createElement("option");   option.value = source.id;   option.textContent =     source.name +     (source.loadedYear ? " · " + source.loadedYear : " · Not loaded");   sourceSelect.append(option); } if ((state.sources || []).some((source) => source.id === sourceId))   sourceSelect.value = sourceId;sourceSelect.disabled=!(state.sources||[]).length;root.querySelector('#calendar-source-refresh').disabled=!sourceSelect.value||pending;

const year=selected.getFullYear(),entries=[...new Map([...years.values()].flatMap(value=>value.entries).map(entry=>[entry.id,entry])).values()],key=dateKey(selected);body.replaceChildren();root.querySelector('#calendar-period').textContent=selected.toLocaleDateString(undefined,{month:'long',year:'numeric'});root.querySelectorAll('[data-calendar-view]').forEach(button=>button.setAttribute('aria-pressed',String(button.dataset.calendarView===view)));
if(view==='year')root.querySelector('#calendar-period').textContent=String(year);
if(view==='year')renderYear(entries,year);else if(view==='month')renderMonth(entries,year);else{const start=view==='week'?shift(selected,-((selected.getDay()+6)%7)):selected;renderTimeline(body,Array.from({length:view==='week'?7:1},(_,index)=>shift(start,index)),entries,view==='day')}
const agenda=root.querySelector('#calendar-agenda-list');agenda.replaceChildren();root.querySelector('#calendar-agenda-heading').textContent=selected.toLocaleDateString(undefined,{weekday:'long',month:'short',day:'numeric'});const todayEntries=entries.filter(entry=>overlaps(entry,key)).sort((a,b)=>a.startTime.localeCompare(b.startTime));agenda.parentElement.hidden=!todayEntries.length;todayEntries.forEach(entry=>agenda.append(entryButton(entry)));if(!todayEntries.length){const empty=document.createElement('p');empty.textContent='No entries for this date.';agenda.append(empty)}
const totals=root.querySelector('#calendar-totals');totals.replaceChildren();root.querySelector('#calendar-totals-heading').textContent='Leave balances · '+year;root.querySelector('#calendar-balances-empty').hidden=state.leaveTypes.length>0;state.leaveTypes.forEach(type=>{const used=entries.filter(entry=>entry.kind==='leave'&&entry.startDate.slice(0,4)===String(year)&&entry.leaveTypeId===type.id).reduce((sum,entry)=>sum+entry.quantity,0),row=document.createElement('tr');paint(row,type.color);const values=[type.name+' ('+type.unit+')',type.count===null?'Not set':String(type.count),String(Number(used.toFixed(4))),type.count===null?'—':String(Number((type.count-used).toFixed(4)))];values.forEach(value=>{const cell=document.createElement('td');cell.textContent=value;row.append(cell)});totals.append(row)});
};
const renderTypes=()=>{const select=field('leaveTypeId'),value=select.value;select.replaceChildren();state.leaveTypes.forEach(type=>{const option=document.createElement('option');option.value=type.id;option.textContent=type.name+' ('+type.unit+')';select.append(option)});if(state.leaveTypes.some(type=>type.id===value))select.value=value;unitChanged();const list=root.querySelector('#calendar-type-list');list.replaceChildren();state.leaveTypes.forEach(type=>{const row=document.createElement('div'),label=document.createElement('span');row.className='calendar-type-row';paint(label,type.color);label.textContent=type.name+' · '+type.unit+' · '+(type.count===null?'No allowance':type.count+' per year');row.append(label,iconButton('edit','Edit leave type',()=>{if(pending)return;editingType=type.id;typeField('name').value=type.name;typeField('unit').value=type.unit;root.querySelector('#calendar-type-unit').textContent='Unit: '+type.unit+'. Saved units are preserved.';typeField('count').step=type.unit==='days'?'0.5':'any';typeField('count').value=type.count===null?'':String(type.count);typeField('color').value=colorHex(type.color);typeField('name').focus()}),iconButton('trash','Delete leave type',()=>request({type:'calendar.type.delete',year:selected.getFullYear(),id:type.id})));list.append(row)})};
field('kind').addEventListener('change',()=>{if(!editing)field('color').value=field('kind').value==='holiday'?'#e29b30':'#3378e6';kindChanged()});field('leaveTypeId').addEventListener('change',unitChanged);root.querySelector('#calendar-cancel').addEventListener('click',closeEntry);root.querySelector('#calendar-delete').addEventListener('click',()=>request({type:'calendar.delete',year:selected.getFullYear(),id:editing}));root.querySelector('#calendar-type-cancel').addEventListener('click',()=>{editingType='';typeForm.reset();root.querySelector('#calendar-type-unit').textContent='Days, including half days. Leave allowance blank for no limit.'});
form.addEventListener('submit',event=>{event.preventDefault();if(pending)return;const kind=field('kind').value,startDate=field('startDate').value,entry={kind,title:field('title').value,startDate,endDate:kind==='plan'?startDate:field('endDate').value,startTime:kind==='plan'?field('startTime').value:'',endTime:kind==='plan'?field('endTime').value:'',agenda:field('agenda').value,color:field('color').value,leaveTypeId:kind==='leave'?field('leaveTypeId').value:'',quantity:kind==='leave'?leaveQuantity():0};if(kind==='leave'){entry.includeWeekends=field('includeWeekends').checked;if(state.leaveTypes.find(type=>type.id===entry.leaveTypeId)?.unit==='days'&&entry.quantity<=0){message('No leave days remain after excluding holidays and selected weekends.',true);return}}if(editing)entry.id=editing;if(entry.endDate<startDate||(kind==='plan'&&entry.endTime<=entry.startTime)||(kind==='leave'&&startDate.slice(0,4)!==entry.endDate.slice(0,4))){message('Check the date range and end time. Split leave across calendar years.',true);return}pendingDate=startDate;request({type:'calendar.save',year:Number(startDate.slice(0,4)),entry})});
typeForm.addEventListener('submit',event=>{event.preventDefault();const leaveType={name:typeField('name').value,unit:typeField('unit').value,count:typeField('count').value===''?null:Number(typeField('count').value),color:typeField('color').value};if(editingType)leaveType.id=editingType;request({type:'calendar.type.save',year:selected.getFullYear(),leaveType})});
root.querySelectorAll('[data-calendar-view]').forEach(button=>button.addEventListener('click',()=>{view=button.dataset.calendarView;savedState.calendarView=view;vscode.setState(savedState);render()}));root.querySelector('#calendar-prev').addEventListener('click',()=>choose(view==='year'?new Date(selected.getFullYear()-1,selected.getMonth(),1,12):view==='month'?new Date(selected.getFullYear(),selected.getMonth()-1,1,12):shift(selected,view==='week'?-7:-1)));root.querySelector('#calendar-next').addEventListener('click',()=>choose(view==='year'?new Date(selected.getFullYear()+1,selected.getMonth(),1,12):view==='month'?new Date(selected.getFullYear(),selected.getMonth()+1,1,12):shift(selected,view==='week'?7:1)));root.querySelector('#calendar-today').addEventListener('click',()=>choose(new Date()));
root.querySelector('#calendar-source-select').addEventListener('change',()=>{root.querySelector('#calendar-source-refresh').disabled=!root.querySelector('#calendar-source-select').value||pending});
root.querySelector('#calendar-source-refresh').addEventListener('click',()=>{const id=root.querySelector('#calendar-source-select').value;if(!id){message('Choose a connected Team Calendar first.',true);return}request({type:'calendar.source.refresh',id,year:selected.getFullYear()})});
window.addEventListener('message',event=>{const incoming=event.data;if(incoming?.type==='calendar.invalidated'){years.clear();state.entries=state.entries.filter(entry=>!entry.sourceId);loadYear(selected.getFullYear());render();return}if(incoming?.type==='shell.state'&&incoming.page==='calendar'){refresh();return}if(incoming?.type==='calendar.error'||(incoming?.type==='protocol.error'&&pending)){loading.clear();lock(false);pendingDate='';pendingAction='';message(incoming.message||'Calendar request failed. Your draft is retained.',true);return}if(!['calendar.state','calendar.saved'].includes(incoming?.type))return;loading.delete(incoming.state.year);if(incoming.type==='calendar.saved'){years.clear();if(pendingDate)selected=fromKey(pendingDate);pendingDate='';lock(false);if(pendingAction==='calendar.save'||pendingAction==='calendar.delete'){reset();dialog.close()}if(pendingAction==='calendar.type.save'){editingType='';typeForm.reset()}message(pendingAction.startsWith('calendar.source.')?'Calendar updated.':'Saved locally.');pendingAction=''}else message('');years.set(incoming.state.year,incoming.state);while(years.size>3)years.delete(years.keys().next().value);if(incoming.state.year===selected.getFullYear()){state=incoming.state;renderTypes()}render()});reset();
})();
`;

export const teamCalendarScript = String.raw`
(()=>{
const form=document.querySelector('#team-calendar-connect'),list=document.querySelector('#team-calendar-list'),status=document.querySelector('#team-calendar-message');
let connecting=false;
const send=(type,id)=>vscode.postMessage({type,id,year:new Date().getFullYear()});
form.addEventListener('submit',event=>{event.preventDefault();if(connecting)return;connecting=true;form.querySelector('button').disabled=true;status.textContent='Enter the iCal URL in the VS Code prompt…';vscode.postMessage({type:'calendar.source.connect',name:form.elements.namedItem('name').value,color:form.elements.namedItem('color').value,holidays:form.elements.namedItem('kind').value==='holidays',year:new Date().getFullYear()})});
const render=sources=>{list.replaceChildren();for(const source of sources){const row=document.createElement('div'),copy=document.createElement('div'),name=document.createElement('strong'),detail=document.createElement('small');row.className='workspace-row';name.textContent=source.name;name.style.borderLeft='3px solid '+(/^#[a-f0-9]{6}$/i.test(source.color)?source.color:'#159d89');name.style.paddingLeft='.4rem';detail.textContent=(source.holidays?'Holidays':'Events')+' · '+(source.loadedYear?'Loaded '+source.loadedYear:'Refresh to load events');copy.append(name,detail);row.append(copy,iconButton('refresh','Refresh '+source.name+' for this year',()=>{status.textContent='Refreshing calendar…';send('calendar.source.refresh',source.id)}),iconButton('trash','Remove '+source.name,()=>send('calendar.source.remove',source.id)));list.append(row)}if(!sources.length){const empty=document.createElement('p');empty.textContent='No connected calendars.';list.append(empty)}};
window.addEventListener('message',event=>{const incoming=event.data;if(incoming?.type==='calendar.sources'){if(connecting){connecting=false;form.querySelector('button').disabled=false;if(!incoming.error)form.reset()}render(incoming.sources||[]);status.textContent=incoming.message||''}else if(['calendar.state','calendar.saved'].includes(incoming?.type)){render(incoming.state.sources||[])}else if(incoming?.type==='protocol.error'&&connecting){connecting=false;form.querySelector('button').disabled=false;status.textContent='Calendar request failed. Try again.'}});
})();
`;
