export const githubStyles = String.raw`
.github-toolbar{display:flex;flex-wrap:wrap;gap:.5rem;padding:1rem}.github-toolbar select,.github-toolbar input{min-width:0;background:var(--panel2);color:var(--text);border:1px solid var(--border);border-radius:.45rem;padding:.55rem}.github-toolbar select{flex:1}.github-toolbar input{flex:2}.github-list{display:grid;gap:.5rem;max-height:24rem;overflow:auto;padding:0 1rem 1rem}.github-row{display:flex;align-items:center;gap:.6rem;justify-content:space-between;background:var(--panel2);border:1px solid var(--border);border-radius:.5rem;padding:.65rem}.github-row-copy{min-width:0}.github-row-copy strong,.github-row-copy small{display:block;overflow-wrap:anywhere}.github-row-copy small{color:var(--muted);font-size:.75rem}.github-row>.icon-button{flex-shrink:0}.github-message{margin:0;padding:0 1rem 1rem;font-size:.8rem;color:var(--muted)}.github-more{margin:0 1rem 1rem}.github-card .github-heading{display:flex;align-items:center;justify-content:space-between}.github-settings-actions{display:flex;gap:.5rem;padding:0 1rem 1rem}
.github-toolbar{display:grid;grid-template-columns:minmax(10rem,1fr) minmax(0,2fr);padding:1rem 1.25rem .75rem;gap:.65rem}.github-toolbar select,.github-toolbar input{width:100%;font-size:.85rem;padding:.65rem}.github-list{padding:.25rem 1.25rem 1rem}.github-list:empty,.github-message:empty{display:none}.github-message{padding:.25rem 1.25rem 1rem}.github-empty{padding:1rem;border:1px dashed var(--border);border-radius:.6rem;text-align:center;font-size:.8rem;margin:0}.github-row{padding:.8rem}.github-settings-actions{justify-content:flex-end;padding:0 1.25rem 1rem}@media(max-width:650px){.github-toolbar{grid-template-columns:minmax(0,1fr)}}
`;
export const githubScript = String.raw`
(()=>{
const make=(tag,className,text)=>{const element=document.createElement(tag);if(className)element.className=className;if(text)element.textContent=text;return element};
const card=make('article','workspace-panel github-card'),heading=make('h2','github-heading','GitHub repositories'),toolbar=make('div','github-toolbar'),owner=make('select'),filter=make('input'),list=make('div','github-list'),message=make('p','github-message'),more=make('button','icon-button github-more','Load more');card.id='github-repositories';owner.setAttribute('aria-label','Repository owner');owner.title='Select your account or an organization';filter.placeholder='Search loaded repositories';filter.setAttribute('aria-label','Search loaded repositories');message.setAttribute('role','status');message.setAttribute('aria-live','polite');more.type='button';more.hidden=true;let state={connected:false,login:'',organizations:[],owner:'',repositories:[],hasMore:false,message:''},pending=false;
const lock=value=>{pending=value;[...card.querySelectorAll('button,select'),...settings.querySelectorAll('button')].forEach(control=>control.disabled=value)};
const request=action=>{if(pending)return;lock(true);message.textContent=action.type==='github.clone'?'Cloning repository…':'Loading GitHub…';vscode.postMessage(action)};
const refresh=iconButton('refresh','Refresh GitHub organizations and repositories',()=>request({type:'github.refresh'}));heading.append(refresh);toolbar.append(owner,filter);card.append(heading,toolbar,message,list,more);document.querySelector('.workspace-grid').append(card);
const settings=make('article','jira-card github-settings'),settingsHeading=make('h2',null,'GitHub'),settingsStatus=make('p','jira-summary','Connect GitHub.com to browse repositories. Your PAT is entered securely in VS Code.'),actions=make('div','github-settings-actions');settings.id='github-settings';actions.append(iconButton('edit','Configure GitHub PAT',()=>request({type:'github.configure'})),iconButton('trash','Disconnect GitHub',()=>request({type:'github.disconnect'})));settings.append(settingsHeading,settingsStatus,actions);document.querySelector('.settings-grid').append(settings);initializeCardLayouts();
const renderList=()=>{list.replaceChildren();const query=filter.value.toLowerCase();state.repositories.filter(repo=>(repo.owner+'/'+repo.name+' '+repo.description).toLowerCase().includes(query)).forEach(repo=>{const row=make('div','github-row'),copy=make('div','github-row-copy'),title=make('strong',null,repo.owner+'/'+repo.name),detail=make('small',null,(repo.private?'Private':'Public')+(repo.archived?' · Archived':'')+(repo.description?' · '+repo.description:''));copy.append(title,detail);row.append(copy,iconButton('folder','Clone '+repo.owner+'/'+repo.name+' and add to Project launcher',()=>request({type:'github.clone',id:repo.id})));list.append(row)});if(state.connected&&!state.repositories.length)list.append(make('p','github-empty',state.owner?'No accessible repositories for this owner.':'Select an account or organization to browse repositories.'));if(state.repositories.length&&!list.children.length)list.append(make('p','github-empty','No repositories match your search.'));more.hidden=!state.hasMore;filter.disabled=!state.connected};
owner.addEventListener('change',()=>{filter.value='';request({type:'github.repositories',owner:owner.value,more:false})});filter.addEventListener('input',renderList);more.addEventListener('click',()=>request({type:'github.repositories',owner:state.owner,more:true}));
window.addEventListener('message',event=>{const incoming=event.data;if(incoming?.type!=='github.state'||!Array.isArray(incoming.state?.repositories)||!Array.isArray(incoming.state?.organizations))return;state=incoming.state;lock(false);owner.replaceChildren();const placeholder=make('option',null,state.login?'Select repository owner':'Refresh to load organizations');placeholder.value='';owner.append(placeholder);[state.login,...state.organizations].filter(Boolean).forEach(name=>{const option=make('option',null,name===state.login?'My repositories ('+name+')':name);option.value=name;owner.append(option)});owner.value=state.owner;owner.disabled=!state.login;refresh.disabled=!state.connected;settingsStatus.textContent=state.connected?'GitHub PAT saved'+(state.login?' · '+state.login:'')+'. Update it here to change access.':'Connect GitHub.com to browse repositories. Your PAT is entered securely in VS Code.';message.textContent=state.message||(state.connected?'':'Connect GitHub in Settings to browse and clone repositories.');renderList()});
vscode.postMessage({type:'github.status'});
})();
`;
