export const jiraReaderScript = String.raw`
const jiraDialog=document.querySelector("#jira-reader"),commentList=document.querySelector("#jira-comments"),commentMessage=document.querySelector("#jira-comment-message"),commentBody=document.querySelector("#jira-comment-body"),commentSubmit=document.querySelector("#jira-comment-submit"),commentMore=document.querySelector("#jira-comment-more");
let jiraReaderKey,commentNext,commentPosting=false,commentLoading=false;
const commentDrafts=new Map();
function openJiraIssue(key){if(commentPosting)return;if(jiraReaderKey)commentDrafts.set(jiraReaderKey,commentBody.value);jiraReaderKey=key;document.querySelector("#jira-reader-title").textContent=key;document.querySelector("#jira-detail").textContent="Loading issue…";commentList.replaceChildren();commentBody.value=commentDrafts.get(key)||"";commentMessage.textContent="Loading comments…";commentNext=undefined;commentMore.hidden=true;commentLoading=true;commentSubmit.disabled=false;if(!jiraDialog.open)jiraDialog.showModal();vscode.postMessage({type:"jira.issue",issueKey:key});vscode.postMessage({type:"jira.comments",issueKey:key,startAt:0})}
function appendJiraComment(comment){if([...commentList.children].some(item=>item.dataset.commentId===comment.id))return;const card=document.createElement("article"),heading=document.createElement("p"),body=document.createElement("div");card.className="jira-comment";card.dataset.commentId=comment.id;heading.textContent=comment.author+" · "+new Date(comment.createdAt).toLocaleString();body.className="reader-article";renderRichContent(body,{html:comment.html});card.append(heading,body);commentList.append(card)}
document.querySelector("#jira-reader-close").addEventListener("click",()=>{if(!commentPosting)jiraDialog.close()});
jiraDialog.addEventListener("cancel",event=>{if(commentPosting)event.preventDefault()});
document.querySelector("#jira-reader-browser").addEventListener("click",()=>{if(jiraReaderKey)vscode.postMessage({type:"jira.open",issueKey:jiraReaderKey})});
document.querySelector("#jira-reader-refresh").addEventListener("click",()=>{if(jiraReaderKey&&!commentPosting)openJiraIssue(jiraReaderKey)});
commentMore.addEventListener("click",()=>{if(commentNext===undefined||commentLoading)return;commentLoading=true;commentMore.disabled=true;vscode.postMessage({type:"jira.comments",issueKey:jiraReaderKey,startAt:commentNext})});
document.querySelector("#jira-comment-form").addEventListener("submit",event=>{event.preventDefault();if(commentPosting||!jiraReaderKey||!commentBody.value.trim())return;commentPosting=true;commentSubmit.disabled=true;commentBody.disabled=true;commentMessage.textContent="Confirm posting in VS Code…";vscode.postMessage({type:"jira.comment.add",issueKey:jiraReaderKey,body:commentBody.value})});
window.addEventListener("message",event=>{const message=event.data;if(message?.issueKey!==jiraReaderKey)return;if(message.type==="jira.comments"){commentLoading=false;commentMore.disabled=false;if(message.startAt===0)commentList.replaceChildren();message.page.comments.forEach(appendJiraComment);commentNext=message.page.nextStartAt;commentMore.hidden=commentNext===undefined;commentMessage.textContent=commentList.childElementCount?"":"No comments yet."}else if(message.type==="jira.comment.result"){commentPosting=false;commentSubmit.disabled=false;commentBody.disabled=false;if(message.comment){appendJiraComment(message.comment);commentBody.value="";commentDrafts.delete(jiraReaderKey);commentMessage.textContent="Comment posted."}else commentMessage.textContent=message.message||"Comment could not be posted."}else if(message.type==="jira.viewer.error"){if(message.target==="issue")document.querySelector("#jira-detail").textContent=message.message;else{commentLoading=false;commentMore.disabled=false;commentMessage.textContent=message.message}}});
`;
