export const walkthroughStyles = String.raw`
.walkthrough{position:fixed;right:1.5rem;top:6rem;z-index:50;width:min(24rem,calc(100vw - 2rem));max-height:calc(100vh - 8rem);overflow:auto;padding:1.4rem;border:1px solid var(--border);border-top:4px solid var(--accent);border-radius:16px;background:var(--panelGradient);box-shadow:var(--shadow)}
.walkthrough[hidden]{display:none}.walkthrough h2{margin:.7rem 0;font-size:1.2rem}.walkthrough p{line-height:1.6;color:var(--muted)}.walkthrough-progress{font-size:.8rem;color:var(--accent);font-weight:700}.walkthrough-actions{display:flex;justify-content:flex-end;gap:.5rem;margin-top:1.2rem}.walkthrough-actions button{border:1px solid var(--border);border-radius:8px;padding:.55rem .8rem;background:var(--panel2);color:var(--text)}.walkthrough-actions .walkthrough-next{background:var(--accent);color:var(--accentText);border-color:var(--accent)}.walkthrough-target{outline:2px dashed var(--accent);outline-offset:4px}
`;

export const walkthroughScript = String.raw`
const tourSteps=[
 {page:"home",title:"Your developer dashboard",text:"Home brings together sticky notes, your current Jira task, frequently used URL groups and application launchers. This guide only navigates pages; it does not create data or run anything."},
 {page:"settings",title:"Connect securely",text:"Set up Jira and Confluence here. Credentials are entered in native VS Code prompts and kept in SecretStorage, never in dashboard forms. Network proxy lets you configure an extension-only proxy and an IT-approved CA bundle if needed."},
 {page:"jira",title:"Follow your work",text:"Sync Jira when needed and use the custom JQL filter above the three-column board. The last filter is remembered. Click an issue for its full-screen details and comments. Local-only cards stay on this device and never sync to Jira."},
 {page:"workspace",title:"Projects and commands",text:"Select project folders with the VS Code picker and open them or their terminals. Save command shortcuts with an optional terminal folder. Running a saved command requires confirmation; visiting this page does not execute commands."},
 {page:"notes",title:"Notes that save as you type",text:"Create a note with a title, then edit its content. Changes save automatically. Home sticky notes open in a centered editor when clicked."},
 {page:"knowledge",title:"Read and bookmark knowledge",text:"Search connected Confluence pages and select one to read its formatted content. Focus reader provides a distraction-free view; the bookmark icon saves a local reference in Notes."},
 {page:"search",title:"Find things and make it yours",text:"Search local notes, projects and cached Jira/Confluence entries. Use the header theme control, floating zoom widget and card grips to customize the dashboard. Replay this tour from the header guide icon or the Show starter guide command."}
];
// Update these highlights alongside release notes when shipping new features.
const updateSteps=[
 {page:"notes",title:"Reliable Confluence bookmarks",text:"Saved references now open after other searches, cache expiry and restart. Focus Reader requires your API credential; browser links use the saved URL without it. Keep the bookmark's original Confluence site configured in Settings."},
 {page:"settings",title:"Safer data and native networking",text:"VS Code-managed networking is now the default for existing installs. Use the Command Palette to Create database snapshot or Restore database snapshot. Ten copies are retained. Close other extension windows before restore; credentials are not backed up. Keep an independent encrypted backup."}
];
const walkthroughPanel=document.createElement("section"),walkthroughProgress=document.createElement("div"),walkthroughTitle=document.createElement("h2"),walkthroughText=document.createElement("p"),walkthroughActions=document.createElement("div");
walkthroughPanel.className="walkthrough";walkthroughPanel.hidden=true;walkthroughPanel.tabIndex=-1;walkthroughPanel.setAttribute("role","region");walkthroughPanel.setAttribute("aria-labelledby","walkthrough-title");walkthroughTitle.id="walkthrough-title";walkthroughProgress.className="walkthrough-progress";walkthroughProgress.setAttribute("aria-live","polite");walkthroughActions.className="walkthrough-actions";
const guideControl=(label,action)=>{const control=document.createElement("button");control.type="button";control.textContent=label;control.title=label;control.setAttribute("aria-label",label);control.addEventListener("click",action);return control};
let walkthroughSteps=tourSteps,walkthroughIndex=0,walkthroughVersion="",walkthroughOriginalPage="home",walkthroughKind="tour";
const guideNavigate=page=>{flushAutosave();selectPage(page);vscode.postMessage({type:"navigation.select",page})};
const clearGuideTarget=()=>document.querySelectorAll(".walkthrough-target").forEach(element=>element.classList.remove("walkthrough-target"));
const closeWalkthrough=()=>{walkthroughPanel.hidden=true;clearGuideTarget();guideNavigate(walkthroughOriginalPage);guideReplay.focus()};
const showGuideStep=()=>{const step=walkthroughSteps[walkthroughIndex];clearGuideTarget();guideNavigate(step.page);const target=document.querySelector('[data-page="'+step.page+'"]');target?.classList.add("walkthrough-target");walkthroughProgress.textContent=(walkthroughKind==="update"?"What's new · ":"Starter guide · ")+walkthroughVersion+" · "+(walkthroughIndex+1)+" of "+walkthroughSteps.length;walkthroughTitle.textContent=step.title;walkthroughText.textContent=step.text;guideBack.disabled=walkthroughIndex===0;guideNext.textContent=walkthroughIndex===walkthroughSteps.length-1?"Finish":"Next";guideNext.title=guideNext.textContent;guideNext.setAttribute("aria-label",guideNext.textContent);walkthroughPanel.hidden=false;walkthroughPanel.focus()};
const guideSkip=guideControl("Skip",closeWalkthrough),guideBack=guideControl("Back",()=>{if(walkthroughIndex>0){walkthroughIndex--;showGuideStep()}}),guideNext=guideControl("Next",()=>{if(walkthroughIndex===walkthroughSteps.length-1)closeWalkthrough();else{walkthroughIndex++;showGuideStep()}});guideNext.className="walkthrough-next";walkthroughActions.append(guideSkip,guideBack,guideNext);walkthroughPanel.append(walkthroughProgress,walkthroughTitle,walkthroughText,walkthroughActions);document.body.append(walkthroughPanel);
const guideReplay=iconButton("book","Replay starter guide",()=>vscode.postMessage({type:"walkthrough.open"}));guideReplay.id="walkthrough-replay";document.querySelector(".header-tools").append(guideReplay);
document.addEventListener("keydown",event=>{if(event.key==="Escape"&&!walkthroughPanel.hidden&&!document.querySelector("dialog[open]")){event.preventDefault();closeWalkthrough()}});
window.addEventListener("message",event=>{const message=event.data;if(message?.type!=="walkthrough.state"||!["tour","update"].includes(message.mode)||typeof message.version!=="string"||message.version.length>50)return;if(walkthroughPanel.hidden)walkthroughOriginalPage=document.querySelector("[data-view]:not([hidden])")?.dataset.view||"home";walkthroughSteps=message.mode==="update"?updateSteps:tourSteps;walkthroughKind=message.mode;walkthroughVersion=message.version;walkthroughIndex=0;showGuideStep()});
`;
